/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--color-background)',
        foreground: {
          DEFAULT: 'var(--color-foreground)',
          muted: 'var(--color-foreground-muted)',
          subtle: 'var(--color-foreground-subtle)',
        },
        brand: {
          DEFAULT: 'var(--color-brand)',
          strong: 'var(--color-brand-strong)',
          deep: 'var(--color-brand-deep)',
          teal: 'var(--color-brand-teal)',
          'teal-strong': 'var(--color-brand-teal-strong)',
          cyan: 'var(--color-brand-cyan)',
          muted: 'var(--color-brand-muted)',
          'teal-muted': 'var(--color-brand-teal-muted)',
        },
        navy: {
          DEFAULT: 'var(--color-navy)',
          2: 'var(--color-navy-2)',
          3: 'var(--color-navy-3)',
        },
        surface: {
          DEFAULT: 'var(--color-surface)',
          alt: 'var(--color-surface-alt)',
          hover: 'var(--color-surface-hover)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
          strong: 'var(--color-border-strong)',
          dark: 'var(--color-border-dark)',
        },
        'on-dark': {
          DEFAULT: 'var(--color-on-dark)',
          muted: 'var(--color-on-dark-muted)',
        },
        nav: {
          DEFAULT: 'var(--color-nav-fg)',
          hover: 'var(--color-nav-hover)',
          user: 'var(--color-nav-user)',
          'user-hover': 'var(--color-nav-user-hover)',
          search: 'var(--color-nav-search)',
          kbd: 'var(--color-nav-kbd)',
        },
        success: {
          DEFAULT: 'var(--color-success)',
          muted: 'var(--color-success-muted)',
        },
        warning: {
          DEFAULT: 'var(--color-warning)',
          muted: 'var(--color-warning-muted)',
        },
        danger: {
          DEFAULT: 'var(--color-danger)',
          muted: 'var(--color-danger-muted)',
          strong: 'var(--color-danger-strong)',
        },
        info: {
          DEFAULT: 'var(--color-info)',
          muted: 'var(--color-info-muted)',
        },
        status: {
          draft: 'var(--color-status-draft)',
          'draft-muted': 'var(--color-status-draft-muted)',
          signed: 'var(--color-status-signed)',
          'signed-muted': 'var(--color-status-signed-muted)',
          submitted: 'var(--color-status-submitted)',
          'submitted-muted': 'var(--color-status-submitted-muted)',
          valid: 'var(--color-status-valid)',
          'valid-muted': 'var(--color-status-valid-muted)',
          invalid: 'var(--color-status-invalid)',
          'invalid-muted': 'var(--color-status-invalid-muted)',
          cancelled: 'var(--color-status-cancelled)',
          'cancelled-muted': 'var(--color-status-cancelled-muted)',
          rejected: 'var(--color-status-rejected)',
          'rejected-muted': 'var(--color-status-rejected-muted)',
        },
      },
      spacing: {
        'token-2xs': 'var(--space-2xs)',
        'token-xs': 'var(--space-xs)',
        'token-sm': 'var(--space-sm)',
        'token-md': 'var(--space-md)',
        'token-lg': 'var(--space-lg)',
        'token-xl': 'var(--space-xl)',
        'token-2xl': 'var(--space-2xl)',
        'button-y': 'var(--space-button-y)',
        'button-x': 'var(--space-button-x)',
        'button-y-sm': 'var(--space-button-y-sm)',
        'button-x-sm': 'var(--space-button-x-sm)',
        'button-y-lg': 'var(--space-button-y-lg)',
        'button-x-lg': 'var(--space-button-x-lg)',
        'input-y': 'var(--space-input-y)',
        'input-x': 'var(--space-input-x)',
        'badge-y': 'var(--space-badge-y)',
        'badge-x': 'var(--space-badge-x)',
        'nav-y': 'var(--space-nav-y)',
        'nav-x': 'var(--space-nav-x)',
        'nav-gap': 'var(--space-nav-gap)',
        'nav-icon': 'var(--space-nav-icon-gap)',
        'topbar-y': 'var(--space-topbar-y)',
        'topbar-x': 'var(--space-topbar-x)',
        'hero-y': 'var(--space-hero-y)',
        'hero-x': 'var(--space-hero-x)',
        'hero-y-sm': 'var(--space-hero-y-sm)',
        'hero-x-sm': 'var(--space-hero-x-sm)',
        'auth-form-y': 'var(--space-auth-form-y)',
        'auth-form-x': 'var(--space-auth-form-x)',
        'auth-form-y-sm': 'var(--space-auth-form-y-sm)',
        'auth-form-x-sm': 'var(--space-auth-form-x-sm)',
        sidebar: 'var(--size-sidebar)',
        'sidebar-collapsed': 'var(--size-sidebar-collapsed)',
        avatar: 'var(--size-avatar)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        pill: 'var(--radius-pill)',
        button: 'var(--radius-button)',
        control: 'var(--radius-control)',
        logo: 'var(--radius-logo)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        brand: 'var(--shadow-brand)',
        'brand-mark': 'var(--shadow-brand-mark)',
        ring: 'var(--ring)',
        'ring-input': 'var(--ring-input)',
        'nav-active': 'var(--shadow-nav-active)',
      },
      backgroundImage: {
        'gradient-brand': 'var(--gradient-brand)',
        'gradient-brand-soft': 'var(--gradient-brand-soft)',
        'gradient-hero': 'var(--gradient-hero)',
        'gradient-hero-text': 'var(--gradient-hero-text)',
        'gradient-hero-glow': 'var(--gradient-hero-glow)',
        'gradient-skeleton': 'var(--gradient-skeleton)',
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        en: ['var(--font-en)', 'var(--font-sans)', 'sans-serif'],
        display: ['var(--font-display)', 'var(--font-sans)', 'sans-serif'],
      },
      fontSize: {
        'token-xs': 'var(--font-size-xs)',
        'token-sm': 'var(--font-size-sm)',
        'token-md': 'var(--font-size-md)',
        'token-lg': 'var(--font-size-lg)',
        'token-xl': 'var(--font-size-xl)',
        page: 'var(--font-size-page)',
        stat: 'var(--font-size-stat)',
        button: 'var(--font-size-button)',
        'button-sm': 'var(--font-size-button-sm)',
        'button-lg': 'var(--font-size-button-lg)',
        badge: 'var(--font-size-badge)',
        'logo-mark': 'var(--font-size-logo-mark)',
        'logo-name': 'var(--font-size-logo-name)',
        'logo-name-sm': 'var(--font-size-logo-name-sm)',
        tagline: 'var(--font-size-tagline)',
        'tagline-sm': 'var(--font-size-tagline-sm)',
        nav: 'var(--font-size-nav)',
        'nav-group': 'var(--font-size-nav-group)',
        'hero-title': 'var(--font-size-hero-title)',
        'hero-title-sm': 'var(--font-size-hero-title-sm)',
        'login-title': 'var(--font-size-login-title)',
        'hero-stat': 'var(--font-size-hero-stat)',
        'hero-chip': 'var(--font-size-hero-chip)',
        'hero-tag': 'var(--font-size-hero-tag)',
      },
      letterSpacing: {
        brand: 'var(--tracking-brand)',
        tagline: 'var(--tracking-tagline)',
        'nav-group': 'var(--tracking-nav-group)',
      },
      width: {
        sidebar: 'var(--size-sidebar)',
        'sidebar-collapsed': 'var(--size-sidebar-collapsed)',
        avatar: 'var(--size-avatar)',
        'auth-form': 'var(--size-auth-form)',
      },
      minHeight: {
        hero: 'var(--size-hero-min)',
        'hero-sm': 'var(--size-hero-min-sm)',
      },
      maxWidth: {
        sidebar: 'var(--size-sidebar)',
        'auth-form': 'var(--size-auth-form)',
        'auth-form-wide': 'var(--size-auth-form-wide)',
      },
    },
  },
  plugins: [],
};
