#!/bin/bash
# Create runtime app role (NOSUPERUSER, NOBYPASSRLS) with password from env.
# Used only by docker-compose.prod.yml — does not replace infra/postgres/init (dev).
set -euo pipefail

: "${POSTGRES_USER:?}"
: "${POSTGRES_DB:?}"
: "${POSTGRES_APP_USER:=einvoice_app}"
: "${POSTGRES_APP_PASSWORD:?POSTGRES_APP_PASSWORD is required}"

# Escape single quotes for SQL string literals: ' → ''
sql_escape() {
  printf "%s" "$1" | sed "s/'/''/g"
}

APP_USER_SQL="$(sql_escape "$POSTGRES_APP_USER")"
APP_PASS_SQL="$(sql_escape "$POSTGRES_APP_PASSWORD")"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${APP_USER_SQL}') THEN
    CREATE ROLE ${POSTGRES_APP_USER} LOGIN PASSWORD '${APP_PASS_SQL}'
      NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
  ELSE
    ALTER ROLE ${POSTGRES_APP_USER} WITH LOGIN PASSWORD '${APP_PASS_SQL}'
      NOSUPERUSER NOBYPASSRLS;
  END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_APP_USER};
GRANT USAGE ON SCHEMA public TO ${POSTGRES_APP_USER};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${POSTGRES_APP_USER};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_APP_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${POSTGRES_APP_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${POSTGRES_USER} IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO ${POSTGRES_APP_USER};
EOSQL
