export const PERMISSIONS = {
  TENANT_MANAGE: 'tenant.manage',
  MEMBERS_VIEW: 'members.view',
  MEMBERS_MANAGE: 'members.manage',
  ROLES_VIEW: 'roles.view',
  ROLES_MANAGE: 'roles.manage',
  BRANCHES_VIEW: 'branches.view',
  BRANCHES_MANAGE: 'branches.manage',
  AUDIT_VIEW: 'audit.view',
  BILLING_VIEW: 'billing.view',
  BILLING_MANAGE: 'billing.manage',
  SETTINGS_CURRENCIES_VIEW: 'settings.currencies.view',
  SETTINGS_CURRENCIES_MANAGE: 'settings.currencies.manage',
  SETTINGS_ETA_VIEW: 'settings.eta.view',
  SETTINGS_ETA_MANAGE: 'settings.eta.manage',
  SETTINGS_ITEM_CODES_VIEW: 'settings.item_codes.view',
  SETTINGS_ITEM_CODES_MANAGE: 'settings.item_codes.manage',
  DOCUMENTS_VIEW: 'documents.view',
  DOCUMENTS_MANAGE: 'documents.manage',
  DEVICES_VIEW: 'devices.view',
  DEVICES_MANAGE: 'devices.manage',
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const DEFAULT_ROLE_NAMES = ['Owner', 'Admin', 'Accountant', 'Viewer'] as const;

export const ROLE_PERMISSION_MATRIX: Record<
  (typeof DEFAULT_ROLE_NAMES)[number],
  PermissionCode[]
> = {
  Owner: Object.values(PERMISSIONS),
  Admin: [
    PERMISSIONS.MEMBERS_MANAGE,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.ROLES_MANAGE,
    PERMISSIONS.ROLES_VIEW,
    PERMISSIONS.BRANCHES_MANAGE,
    PERMISSIONS.BRANCHES_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.SETTINGS_CURRENCIES_VIEW,
    PERMISSIONS.SETTINGS_CURRENCIES_MANAGE,
    PERMISSIONS.SETTINGS_ETA_VIEW,
    PERMISSIONS.SETTINGS_ETA_MANAGE,
    PERMISSIONS.SETTINGS_ITEM_CODES_VIEW,
    PERMISSIONS.SETTINGS_ITEM_CODES_MANAGE,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_MANAGE,
    PERMISSIONS.DEVICES_VIEW,
    PERMISSIONS.DEVICES_MANAGE,
  ],
  Accountant: [
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.BRANCHES_VIEW,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.BILLING_MANAGE,
    PERMISSIONS.SETTINGS_CURRENCIES_VIEW,
    PERMISSIONS.SETTINGS_ITEM_CODES_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_MANAGE,
    PERMISSIONS.DEVICES_VIEW,
  ],
  Viewer: [
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.ROLES_VIEW,
    PERMISSIONS.BRANCHES_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW,
  ],
};
