/**
 * Must stay in sync with apps/api/src/imports/import-schema.ts
 * IMPORT_REQUIRED_FIELDS (row-level required for one-row-per-line template).
 */
export const IMPORT_REQUIRED_FIELDS = [
  'internalID',
  'dateTimeIssued',
  'receiverId',
  'receiverName',
  'description',
  'itemCode',
  'quantity',
  'unitPrice',
] as const;

/** Common optional columns shown in the mapping UI (full set auto-maps from template). */
export const IMPORT_COMMON_OPTIONAL_FIELDS = [
  'documentType',
  'branchCode',
  'currencyCode',
  'receiverType',
  'receiverGovernate',
  'receiverRegionCity',
  'receiverStreet',
  'receiverBuildingNumber',
  'itemType',
  'unitType',
  'discountAmount',
  'discountRate',
  'extraDiscountAmount',
  'references',
  'taxType1',
  'taxSubType1',
  'taxRate1',
  'taxAmount1',
  'taxType2',
  'taxSubType2',
  'taxRate2',
  'taxAmount2',
  'taxType3',
  'taxSubType3',
  'taxRate3',
  'taxAmount3',
] as const;

export const IMPORT_FIELD_AR: Record<string, string> = {
  internalID: 'الرقم الداخلي',
  dateTimeIssued: 'تاريخ الإصدار',
  receiverId: 'رقم تسجيل المستلم',
  receiverName: 'اسم المستلم',
  description: 'وصف الصنف',
  itemCode: 'كود الصنف',
  quantity: 'الكمية',
  unitPrice: 'سعر الوحدة',
  documentType: 'نوع المستند',
  branchCode: 'كود الفرع',
  currencyCode: 'عملة البيع',
  receiverType: 'نوع المستلم',
  receiverGovernate: 'محافظة المستلم',
  receiverRegionCity: 'مدينة المستلم',
  receiverStreet: 'شارع المستلم',
  receiverBuildingNumber: 'مبنى المستلم',
  itemType: 'نوع كود الصنف',
  unitType: 'وحدة القياس',
  discountAmount: 'قيمة الخصم',
  discountRate: 'نسبة الخصم',
  extraDiscountAmount: 'خصم إضافي على المستند',
  references: 'الرقم المرجعي للمستند الأصلي',
  taxType1: 'نوع الضريبة 1',
  taxSubType1: 'النوع الفرعي 1',
  taxRate1: 'نسبة الضريبة 1',
  taxAmount1: 'قيمة الضريبة 1',
  taxType2: 'نوع الضريبة 2',
  taxSubType2: 'النوع الفرعي 2',
  taxRate2: 'نسبة الضريبة 2',
  taxAmount2: 'قيمة الضريبة 2',
  taxType3: 'نوع الضريبة 3',
  taxSubType3: 'النوع الفرعي 3',
  taxRate3: 'نسبة الضريبة 3',
  taxAmount3: 'قيمة الضريبة 3',
};

